<a href="https://colab.research.google.com/github/Divij6/MachineLearningPractice/blob/main/SoftMax_Activation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import numpy as np
import math
from sklearn.datasets import make_blobs

In [2]:
def softmax(z):
  ez = np.exp(z)
  sm = ez / np.sum(ez)
  return sm

In [3]:
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

In [4]:
model = Sequential(
    [
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'softmax')    # < softmax activation here
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.001),
)

model.fit(
    X_train,y_train,
    epochs=10
)


Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 1.0929
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4496
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2002
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1140
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0797
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0632
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0530
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0468
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0420
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0381


In [5]:
p_nonpreferred = model.predict(X_train)
print(p_nonpreferred [:2])
print("largest value", np.max(p_nonpreferred), "smallest value", np.min(p_nonpreferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[2.9206078e-03 1.2414122e-02 9.6206826e-01 2.2596985e-02]
 [9.9715728e-01 2.8403711e-03 1.6800977e-06 6.3417082e-07]]
largest value 0.99999815 smallest value 3.3819988e-10


In [6]:
preferred_model = Sequential(
    [
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'linear')   #<-- Note
    ]
)
preferred_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),  #<-- Note
    optimizer=tf.keras.optimizers.Adam(0.001),
)

preferred_model.fit(
    X_train,y_train,
    epochs=10
)


Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 1.7713
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7184
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4211
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2351
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1467
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1021
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0804
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0684
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0607
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0552


In [7]:
p_preferred = preferred_model.predict(X_train)
print(f"two example output vectors:\n {p_preferred[:2]}")
print("largest value", np.max(p_preferred), "smallest value", np.min(p_preferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
two example output vectors:
 [[-1.4630895  -2.8815906   2.7443023   0.21488112]
 [ 6.9528737   2.3043299   0.6751231  -9.133446  ]]
largest value 14.076978 smallest value -14.070406


In [8]:
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"two example output vectors:\n {sm_preferred[:2]}")
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

two example output vectors:
 [[1.3554205e-02 3.2811563e-03 9.1058618e-01 7.2578408e-02]
 [9.8867643e-01 9.4671063e-03 1.8563583e-03 1.0205977e-07]]
largest value 0.9999675 smallest value 1.2656218e-12


In [11]:
for i in range(5):
    print( f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])} ||||||| {p_nonpreferred[i]}, category: {np.argmax(p_nonpreferred[i])}")

[-1.4630895  -2.8815906   2.7443023   0.21488112], category: 2 ||||||| [0.00292061 0.01241412 0.96206826 0.02259699], category: 2
[ 6.9528737  2.3043299  0.6751231 -9.133446 ], category: 0 ||||||| [9.9715728e-01 2.8403711e-03 1.6800977e-06 6.3417082e-07], category: 0
[ 5.066294    2.233633    0.33075455 -7.306193  ], category: 0 ||||||| [9.7237784e-01 2.7532106e-02 6.6228873e-05 2.3758843e-05], category: 0
[-0.5377693  4.060237  -1.4951395 -4.5237594], category: 1 ||||||| [0.00293787 0.9913892  0.00290868 0.00276419], category: 1
[ 0.5509908 -4.5015244  5.2423677 -2.800417 ], category: 2 ||||||| [2.7546245e-03 3.5899265e-03 9.9276203e-01 8.9336646e-04], category: 2
